### ISSUE TITLE
Diviner Second Edition

### ISSUE THREAD

**Issue by elkelks** [ksokhan/gloom-cards#14]
Hey, great work, but could you add the second edition diviner, that was released with the reprint of forgotten circles?

https://boardgamegeek.com/filepage/203897/diviner-2nd-printing-ability-cards-collated-printi

**Comment by ksokhan** [comment]
@elkelks I believe these have been updated a few days ago in #13. Mind doing a hard refresh on the app and seeing if they update for you?
