### ISSUE TITLE
Mindthief Feedback Loop Text Outdated

### ISSUE THREAD

**Issue by Tenebrae-Aeternae** [ksokhan/gloom-cards#4]
Looks like most of the cards have their 2nd Edition text, but this one still has 1e with move 3 jump instead of the 2e move 4 jump

**Comment by Tenebrae-Aeternae** [comment]
Also, if I may post a suggestion, I'd love a dark mode.  I strongly dislike reading on websites with bright white backgrounds

**Comment by ksokhan** [comment]
Thanks for the catch, will update when I get some time.

Would love a dark mode, but unfortunately dont think I'll get some spare time to add this. Youre welcome to submit a pr with dark mode!

**Comment by Tenebrae-Aeternae** [comment]
I don't really know how to do anything involving website coding, but maybe I'll find a way given enough time.  Also quick thanks for your website; I love having the cards laid out as they are here! Even though it's missing some classes, I still use it all the time for the ones available

**Comment by ksokhan** [comment]
FYI @Tenebrae-Aeternae found a bit of time to add dark mode, thanks for the suggestion. It mirrors your OS dark/light preference.

**Comment by Tenebrae-Aeternae** [comment]
Thank you, ksokhan. I also noticed that all the classes are now listed, too. That's been a big help. Thanks again for all your work!

**Comment by rsmorgan91** [comment]
> Looks like most of the cards have their 2nd Edition text, but this one still has 1e with move 3 jump instead of the 2e move 4 jump

This still seems to be the 1e card. This is also on the Silent Scream card as well.

**Comment by ksokhan** [comment]
@rsmorgan91 Im not sure when I'll be able to get to addressing this, but I will happily accept PRs :)
