### ISSUE TITLE
Forgotten Circles: Diviner 2nd printing

### ISSUE THREAD

**Issue by SoccerCore11** [ksokhan/gloom-cards#9]
Could you update the Diviner for the 2nd printing of Forgotten Circles? How can I help with this? Export the cards from Any2Cards?

**Comment by ksokhan** [comment]
Hey @SoccerCore11 
Yes just grabbing the the changed cards from any2cards would be great. If you want to submit a PR that would be even better!

**Comment by SoccerCore11** [comment]
I created a PR, new to this so hopefully I did it right. Would you accept a PR for Envelope X also?

**Comment by ksokhan** [comment]
Yea, see convo here: https://github.com/ksokhan/gloom-cards/issues/5#issuecomment-622996990
Basically if I include it, im spoiling it for others just by including it in the list of characters.
